### PR TITLE
Fixed Filter/Sort Modal

### LINKED ISSUE #169: React Component: Filter/Sort Modal Fix
Make the Filter/Sort Modal load without breaking the page.

### PR DESCRIPTION
**Pull request by Spawbreaker**
- Modal now loads properly
- Checkboxes display text properly now 
image

Should close #169

### CODE REVIEW

File: src/components/filter-sort-modal/filter-sort-modal.jsx [hunk 1]
```diff
@@ -126,24 +71,24 @@ const FilterSortModal = props => {
...
         />
       );
     });
   };
   const handleCheckboxMark = e => {
-    console.log(e.target);
     const target = e.target.id;
-    var filter = modalState.filter;
-    filter.forEach((value, index, array) => {
+    var _filter = filter.value;
```
Comment (christianahvilla) [inline src/components/filter-sort-modal/filter-sort-modal.jsx]: Please rename this variable, it is not a good practice use "_"  in variable name

Comment (Spawbreaker) [reply src/components/filter-sort-modal/filter-sort-modal.jsx]: Should be fixed in the latest commit
